### ISSUE TITLE
Create Jenkins job to run tests

### ISSUE THREAD

**Issue by dsummersl** [myhpom/MyHPOM#115]
Add support for launching tests for pull requests - https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin

Ideally include support for github's 'branch protection' feature as well (run tests on the branch, and then also run tests if the branch were merged)

**Comment by cbcunc** [comment]
myhpom-build.edc.renci.org is ready for you.

**Comment by dsummersl** [comment]
I've setup basic build support. It isn't as yet integrated into github pull requests: http://myhpom-ci.edc.renci.org/jenkins/job/Build_MYHPOM

**Comment by dsummersl** [comment]
(and the build took an hour and twelve minutes)

**Comment by cbcunc** [comment]
Latest run says: Ran 727 tests in 3407.139s. That's some better.

**Comment by cbcunc** [comment]
@dsummersl , I moved the milestone so we're all comfortable.

**Comment by dsummersl** [comment]
This has been set up so that any new PR will kick off a jenkins run - see https://github.com/ResearchSoftwareInstitute/MyHPOM/pull/141 as an example of this.

Jobs are pretty slow at the moment (an hour) so we'll probably have to be a little careful about not pushing to our PRs too many times (every new push will kick off a CI run on the myhpom-build server...which as I said takes an hour), but its definitely a good start!
