### ISSUE TITLE
Migrate to myhpom-service user

### ISSUE THREAD

**Issue by cbcunc** [myhpom/MyHPOM#120]
Migrate MyHpom builds to use the new myhpom-service user instead of xdci-service. To see the secret UID, login to any MyHpom machine and `getent passwd myhpom-service`

Both xdci-service and myhpom-service are members of the same "service accounts" group (group name actually has embedded space, go figure). This should have no effect on this issue.

**Comment by cbcunc** [comment]
Precursor issue to #121.

**Comment by dsummersl** [comment]
I had trouble setting up SSH access for this user. I want to give access to myhpom-service so that jenkins can connect via SSH and do deployments/builds/etc.

I set up the SSH ~/.ssh/authorized_keys for myhpom-service in the same way I did for the xdci-service account:

```shell
sudo ls -alh /home/xdci-service/.ssh                                                             
[sudo] password for dsummers:                                                                                             
total 12K                                                                                                                 
drwx------ 2 xdci-service service accounts   46 Mar  9 12:15 .
drwx------ 9 xdci-service service accounts 4.0K Mar 12 15:28 ..
-rw------- 1 xdci-service service accounts  407 Mar  9 11:42 authorized_keys
-rw-r--r-- 1 xdci-service service accounts  803 Mar  9 12:15 known_hosts
[dsummers@myhpom-dev ~]$ sudo ls -alh /home/myhpom-service/.ssh
total 4.0K                                                   
drwx------ 2 myhpom-service service accounts  28 Mar 27 11:15 .
drwx------ 3 myhpom-service service accounts  90 Mar 26 12:47 ..
-rw------- 1 myhpom-service service accounts 407 Mar 26 12:49 authorized_keys
```

Both authorized key files have the same md5sum.

I then tried to connect to both the xdci-service and myhpom-service:
```
ssh -i ex.private xdci-service@localhost                                                         Last login: Tue Mar 27 11:32:18 2018 from localhost
                                                                                                                           _|_|_|    _|_|_|_|  _|      _|    _|_|_|  _|_|_|
 _|    _|  _|        _|_|    _|  _|          _|                                                                            _|_|_|    _|_|_|    _|  _|  _|  _|          _|
 _|    _|  _|        _|    _|_|  _|          _|                                                                           
 _|    _|  _|_|_|_|  _|      _|    _|_|_|  _|_|_|                                                                         

[xdci-service@myhpom-dev ~]$ exit
logout
Connection to localhost closed.
[dsummers@myhpom-dev ~]$ ssh -i ex.private myhpom-service@localhost
Connection closed by ::1
```

But connections for myhpom-service fail. I noticed the following error in /var/log/secure:

```shell
Mar 27 13:42:12 myhpom-dev sshd[8479]: Accepted publickey for xdci-service from ::1 port 52192 ssh2: RSA 94:9d:67:f0:37:c8:62:ff:a5:e3:a4:63:cf:7a:1d:1a
Mar 27 13:42:12 myhpom-dev sshd[8479]: pam_unix(sshd:session): session opened for user xdci-service by (uid=0)
Mar 27 13:42:16 myhpom-dev sshd[8481]: Received disconnect from ::1: 11: disconnected by user
Mar 27 13:42:16 myhpom-dev sshd[8479]: pam_unix(sshd:session): session closed for user xdci-service
Mar 27 13:42:21 myhpom-dev sshd[8501]: pam_sss(sshd:account): Access denied for user myhpom-service: 6 (Permission denied)
Mar 27 13:42:21 myhpom-dev sshd[8501]: fatal: Access denied for user myhpom-service by PAM account configuration [preauth]
```

**Comment by cbcunc** [comment]
Ticket filed: https://help.renci.org/SelfService/Display.html?id=454

**Comment by dsummersl** [comment]
@cbcunc it works now, thanks!

**Comment by cbcunc** [comment]
RENCI ticket closed.

**Comment by dsummersl** [comment]
I've migrated all the existing jenkins scripts over to the myhpom-service account. I have also updated the myhpom-build and myhpom-dev to user the myhpom-service account.

Once https://github.com/ResearchSoftwareInstitute/MyHPOM/pull/141 is approved and merged I can go ahead and rerun this ansible script (or you could @cbcunc!) to set up the myhpom-service user correctly in production, and then do a deploy.

**Comment by cbcunc** [comment]
@dsummersl Build checks are still running. Once done I'll approve and let you know. I assume you are running the ansible script under Jenkins control? Which job?

**Comment by dsummersl** [comment]
I didn't get to actually migrating all the jenkins jobs over to using ansible directly, so its just a plain shell script as per the others. The job is 'PR_Test_MYHPOM' and is basically a copy of the 'Test_MYHPOM' task, except that it monitors github for PRs (and you can't manually kick it off).

**Comment by dsummersl** [comment]
I've made this deploy to production - because part of the pull request is in the #141 pull request (change production settings to use new directories for SSL directories and the uid codes), I manually updated the .env file in production for the time being - in the unlikely case we need to redeploy v1.0 then we'll need to keep this in mind (otherwise we should be fine as these settings will be in the next release).
