### ISSUE TITLE
Meet between Caktus and RENCI to better discuss use cases, UI, roadmap

### ISSUE THREAD

**Issue by cbcunc** [myhpom/MyHPOM#130]
@wclenhardt  When release 1.0 is done (today!) the developers, that is, Caktus and I, think it would behoove us to see if we can more formally map out what we're trying to deliver in MyHPOM. Iterative development is OK. It works for me. But for customer satisfaction, having a clearer idea of where we are going would be a win.

**Comment by cbcunc** [comment]
@wclenhardt Caktus will l be here Monday afternoon for iRODS Boot Camp. We should grab a second during a break to agree on a good time to meet for this purpose. @Dane is versed in helping scope projects.

**Comment by wclenhardt** [comment]
OK, I'm free at the moment all day (3/26), except for 4 - 5 pm.

Just let me know what time you'd like to get together.  Thx.

**Comment by cbcunc** [comment]
Whenever Terrell lets us have a break. It won't take five minutes. Just want to run an idea up the flagpole with you and the Caktus gang.

**Comment by cbcunc** [comment]
Doodle poll sent for meeting late next week.

**Comment by cbcunc** [comment]
We met and have a workshop with TCC scheduled for 5/4.
