### ISSUE TITLE
Consider migrating to another GitHub organization

### ISSUE THREAD

**Issue by cbcunc** [myhpom/MyHPOM#134]
I have secured  https://github.com/myhpom as a GitHub organization. Given that this project may be maintained by outside groups, evaluate whether we should move MyHPOM development to that organization. Would this require a re-init of the repo? If so, can we continue to merge changes to and from  Hydroshare? Do we have to remain a fork of HS and xDCIShare?

**Comment by dsummersl** [comment]
You could transfer ownership of this repository to your new myhpom organization. I think the issue tracker/wiki/codebase are all transferred when you use that method. Tracking changes from the hydroshare repository would remain the same (using an upstream branch for it) and because myhpom is already a fork or xdci/hydroshare it'll still be a fork (I've transferred ownership of a couple other github projects that were forks of other projects and they retained the little 'forked from' moniker you see on the website).

**Comment by dsummersl** [comment]
Note that we'll all need to update our local git repositories to track the new URL that the project will have, and the SSH access key used by jenkins will need to be added to the new organization (and the jenkins repository settings will also have to be updated).

**Comment by cbcunc** [comment]
I tested this on a couple of dummy orgs and it works, even for deploy keys, integrations, etc., all except for the teams as teams are an org feature, not a repo feature, so they don't get moved. I've sent invitations to everyone on the team and will recreate the team when the repo moves to the new organization.

**Comment by cbcunc** [comment]
Also, refer to https://help.github.com/articles/about-repository-transfers/

> All links to the previous repository location are automatically redirected to the new location. When you use `git clone`, `git fetch`, or `git push` on a transferred repository, these commands will redirect to the new repository location or URL. However, to avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using `git remote` on the command line:

`git remote set-url origin new_ur`l

> For more information, see "Changing a remote's URL (https://help.github.com/articles/changing-a-remote-s-url)".

**Comment by dsummersl** [comment]
So then as a part of this ticket it looks like we can do this?
 - [x] Migrate to the new organization
 - [x] Make sure everyone updates their local git repositories, using the docs Chris provided.
 - [x] Update the Jenkins git paths.
 - [x] close this ticket.

**Comment by cbcunc** [comment]
@dsummersl Repo moved. Time to update Jenkins. You should take that role.

**Comment by dsummersl** [comment]
The command to swap your origin for the new one is:

    git remote set-url origin git@github.com:myhpom/MyHPOM.git

**Comment by cbcunc** [comment]
Please run the following in your myhpom projects to switch to the new myhpom organization git repository:

```
git remote set-url origin git@github.com:myhpom/MyHPOM.git
# verify that your origin has been updated:
git remote -v
# origin  git@github.com:myhpom/MyHPOM.git (fetch)
# origin  git@github.com:myhpom/MyHPOM.git (push)
```
