### ISSUE TITLE
Fix Clocks

### ISSUE THREAD

**Issue by cbcunc** [myhpom/MyHPOM#140]
Fix the clocks on prod, dev, jenkins, and any other machines to sync with timezone.

**Comment by dsummersl** [comment]
Once the above PR is merged the timezone within the myhpom website will be eastern time.

For the jenkins server I installed a post-init script to set the timezone to eastern time: https://wiki.jenkins.io/display/JENKINS/Change+time+zone (times now show up as eastern on jenkins and will continue to do so across restarts)

I manually logged on to the servers and verified that ntpd is running and that the times were correct.

**Comment by cbcunc** [comment]
Merged in #157. We are going to revisit this in the upcoming workshop.
