### ISSUE TITLE
Change menu header

### ISSUE THREAD

**Issue by wclenhardt** [myhpom/MyHPOM#31]
Update top NavBar to reflect MyHPOM categories and wording. 

- The  nav items will point to existing functionality, this is basically just a re-labeling except for the ‘About  MyHPOM’.  FAQs is the replacement for ‘Help’

- We discussed making the ‘About MyHPOM’ a tab in the FAQ page.

Nav Bar Categories and order:
Logo / About MyHPOM / My Profile / My Documents / My Connections / FAQs]

**Comment by cbcunc** [comment]
@wclenhardt As the site has no nav bar, I assume we are talking about the title tab which currently reads "Share and Collaborate | Hydroshare." I understand about the change from Hydroshare to MyHPOM. But with what wording do you want to replace "Share and Collaborate." "Express Your Wishes?" "My Health Peace of Mind?"

**Comment by wclenhardt** [comment]
Here's a crosswalk from old to new:

My Resources -> My Documents
Collaborate -> My Connections
Help -> FAQs

Add:
'About MyHPOM' this should link to a tab on the FAQ page.  I thought I had text for that, but I have to find it.  So for now, the 'About MyHPOM' can link to the FAQ page.

Let me know if this helps or not.  Thx.

**Comment by wclenhardt** [comment]
OK, here's a text file with content for an 'About MyHPOM'.  The notion for this was to add it as it's own tab on the FAQ page.  Can the About item in the header point directly to the relevant tab on the FAQ page?

Thanks!
[About MyHPOM.txt](https://github.com/ResearchSoftwareInstitute/MyHPOM/files/1249620/About.MyHPOM.txt)

**Comment by cbcunc** [comment]
Deployed #41 to myhpom.renci.org. More on the way.

**Comment by cbcunc** [comment]
Merged in #41, #42, and #43. Deployed to myhpom.renci.org. Reviewed with @wclenhardt.
