### ISSUE TITLE
Change all references to Hydroshare or xDCI to MyHPOM

### ISSUE THREAD

**Issue by wclenhardt** [myhpom/MyHPOM#32]
Change all references to Hydroshare or xDCI to MyHPOM
FWIW, I'm referencing the site available to the web.

- Site name that shows up in tab still says ‘<pagename> | hydroshare’
- There are buttons that need to have updated text, e.g. the button on the sign-up page has xDCishare.
- Substitute reference to CUAHSI in copyright statement with ‘The Carolinas Center’ and update year to 2017
- Change ‘This is xDCIShare version DEVELOPMENT’ to swap in MyHPOM
- Look around for any other references, e.g. the site map page refers to xDCIShare

**Comment by cbcunc** [comment]
LC_CTYPE=C && LANG=C && find . -type f | grep -v "\\./\\..*" | xargs grep -l "xDCIShare" | xargs sed -e "s/xDCIShare/MyHPOM/g" -i ".sedbak"

**Comment by cbcunc** [comment]
Merged in #36.

**Comment by cbcunc** [comment]
Deployed to myhpom.renci.org
