### ISSUE TITLE
Update MyHPOM logo

### ISSUE THREAD

**Issue by wclenhardt** [myhpom/MyHPOM#38]
We have a new logo and I can provide a graphic file.  Do you have specs on the pixel dimensions, etc.?  I'm include two screen grabs in .png. Logo with Name, and just the logo.  Don't know if you can use these or need different specs.

<img width="166" alt="tmp_logo_icon" src="https://user-images.githubusercontent.com/8183172/29715365-150ea964-8975-11e7-86bc-5f6de816885c.png">
<img width="300" alt="tmp_logo_full" src="https://user-images.githubusercontent.com/8183172/29715366-1517439e-8975-11e7-964d-0183f1f92eb4.png">

**Comment by cbcunc** [comment]
Please send the originals. I convert them to various scales.

Very nice logo, BTW.

--
Sincerely,

Chris Calloway
Applications Analyst
University of North Carolina
Renaissance Computing Institute
(919) 599-3530


On 8/25/17, 9:10 AM, "Chris Lenhardt" <notifications@github.com<mailto:notifications@github.com>> wrote:


We have a new logo and I can provide a graphic file. Do you have specs on the pixel dimensions, etc.? I'm include two screen grabs in .png. Logo with Name, and just the logo. Don't know if you can use these or need different specs.

[mp_logo_icon]<https://user-images.githubusercontent.com/8183172/29715365-150ea964-8975-11e7-86bc-5f6de816885c.png>

[mp_logo_full]<https://user-images.githubusercontent.com/8183172/29715366-1517439e-8975-11e7-964d-0183f1f92eb4.png>

**Comment by wclenhardt** [comment]
We don’t have originals yet. But will send as soon as we get them.

I agree on the logo!

**Comment by cbcunc** [comment]
How long will it take to get the originals? I’m just trying to avoid doing it twice. If it will take more than a day, then I’ll try to get it in today and do it again later.

--
Sincerely,

Chris Calloway
Applications Analyst
University of North Carolina
Renaissance Computing Institute
(919) 599-3530


On 8/25/17, 10:05 AM, "Chris Lenhardt" <notifications@github.com<mailto:notifications@github.com>> wrote:

We don’t have originals yet. But will send as soon as we get them.

I agree on the logo!

**Comment by wclenhardt** [comment]
I think Josh is on vacation so unfortunately we don't have a fixed date at the moment. Sorry.

**Comment by cbcunc** [comment]
Merged in #39.
