### ISSUE TITLE
Modify signup page

### ISSUE THREAD

**Issue by cbcunc** [myhpom/MyHPOM#40]
Add mobile number, address (optional), zip code (required), and last four digits of SSN. (Make everything except address mandatory?)

**Comment by wclenhardt** [comment]
Update to the initial item. For the sign-up page we only need to add 
'Zip code (primary residence)'.    

Other profile info will be added to profile later in user workflow.

**Comment by cbcunc** [comment]
There's a PR #64 for this that @alexlemann left. It has conflicts. Look at this first to see that it meets our needs after fixing the conflict. There is also a corresponding issue #69 to display this data and more on the profile page. Keep this in sync with that issue by adding the additional fields also requested on the profile page to the signup page.

**Comment by wclenhardt** [comment]
Unless it creates a burden, I was hoping to keep the additional fields as things to be added later, that is not part of the initial account creation process.  The goal was/is to keep the signup part as simple as possible, and to add more information as more functionality is accessed.

So let's say we have the user start with the bare minimum.  The additional fields may be displayed in the profile, but they wouldn't need to be filled out until the user accessed functionality like uploading or sharing a document. Then as part of the resource submission process, initiate a check to see if certain profile fields have been provided by the user.  If yes, then submission goes forward, if no, user is prompted to add additional information.

This is analogous to the Hydroshare requirement to fill in certain metadata before the system will allow you to share the resource.

Let me know if you want to discuss further and/or have me map this out in greater detail.  

Thx!

**Comment by dsummersl** [comment]
I've just updated Alex's old PR to fix conflicts with the main branch - it adds a 'zip code' to the user signup page.

It sounds like to finish this ticket then, we need to:
 * remove the zip code from the user signup form.
 * add it to the account profile page (in the 'about user' section).

**Comment by cbcunc** [comment]
@wclenhardt I'll come talk to you about this tomorrow as there are more than one ticket dealing with this and I want to be straight about what is requested.

**Comment by cbcunc** [comment]
@wclenhardt and I decided to close this issue and not merge #64. We will defer all additional fields to the profile page, which @wclenhardt will finalize next week and capture in #69.
