### ISSUE TITLE
Add item to menu options in header

### ISSUE THREAD

**Issue by wclenhardt** [myhpom/MyHPOM#46]
Please add, or re-enable, the menu option for 'Discover' in the header.  For now, the Discover option can link to a simple page with default MyHPOM page layout and with the following text added as the body:

**"In a future development phase for My Health Peace of Mind, the ability to search and discover new resources relevant to your health care planning will be added.

Once you identify new information the goal is to enable the ability to add the new information to your personal set of resources and/or to share within your network."**

Thanks!

**Comment by cbcunc** [comment]
Merged in #51 and deployed to myhpom.renci.org.
