### ISSUE TITLE
Modify FAQ to accept parameters

### ISSUE THREAD

**Issue by cbcunc** [myhpom/MyHPOM#48]
..for about and help so that we can expand the appropriate tab and panel for each.

**Comment by wclenhardt** [comment]
Update on this one. Client would like the 'About' info as a separate page.  Fears the other tabs that show plus the other language on the page will confuse users if they want to see the 'About' info.  If possible, can we convert the About tab to a separate page and link that to the menu item in the header.  

Also, they have provided a new version of text for the About page.  I'm uploading the file as .docx as there is some suggested formatting and a link.  If you'd like it in some other format, just let  me know.

  Thanks!

[About MyHPOM_v1_20170907_cbm.docx](https://github.com/ResearchSoftwareInstitute/MyHPOM/files/1285343/About.MyHPOM_v1_20170907_cbm.docx)

**Comment by cbcunc** [comment]
That's a better plan than passing parameters to the FAQ page and will save us a lot of work. Thank you. I may have this done by the end of today. Trying to interleave a few other things.

**Comment by cbcunc** [comment]
Merged in #49.

**Comment by cbcunc** [comment]
Deployed on myhpom.renci.org.
