### ISSUE TITLE
Relabel tab "Intro to ..." and Convert  Glossary tab to FAQ

### ISSUE THREAD

**Issue by wclenhardt** [myhpom/MyHPOM#50]
Please relabel the "Intro to MyHPOM" to "FAQs" and Convert tab "Get Started with..." to "Glossary" and add the content of the attached file as is, no need to convert to expandable sections.

[MyHPOM Common Terms 2017090.docx](https://github.com/ResearchSoftwareInstitute/MyHPOM/files/1289460/MyHPOM.Common.Terms.2017090.docx)

**Comment by cbcunc** [comment]
Should the common terms replace all the content in Glossary or simply add to the existing content?

**Comment by wclenhardt** [comment]
Under the renamed tab, now "Glossary", replace all existing content with the glossary content.  Thx!

**Comment by cbcunc** [comment]
Do you mind if the terms are in expandable sections to keep a consistent interface? The OCD part of me is asking.

**Comment by wclenhardt** [comment]
Actually I asked that question, and the preferred format is to put the content in altogether and to not break it up in expandable sections.  Personally, I would have preferred the latter.  Thx.

**Comment by cbcunc** [comment]
Merged in #51 and deployed to myhpom.renci.org.
