### ISSUE TITLE
Remove CUAHSI copyright references in footer

### ISSUE THREAD

**Issue by wclenhardt** [myhpom/MyHPOM#56]
Please update copyright info to (C) 2017 and remove references to UNC and CUAHSI.  I need to double check contract regarding copyright assignment.

**Comment by cbcunc** [comment]
It wouldn't be legal to remove the previous copyright. What you'll have is a trail of copyrights leading to the present. See the footer here: https://xdcishare.renci.org/

**Comment by wclenhardt** [comment]
OK, fair enough let's include the chain of copyright.

**Comment by alexlemann** [comment]
assigned @cbcunc based on our convo. Feel free to reassign if needed.

**Comment by wclenhardt** [comment]
Dealt with by modifying to show copyright history.
