### ISSUE TITLE
Add small info icon next to zip code field on sign-up page

### ISSUE THREAD

**Issue by wclenhardt** [myhpom/MyHPOM#57]
Functionality needed is either a click or mouseover pop-up with explanatory text to be provided by TCC team explaining why a zip code is required.

**Comment by cbcunc** [comment]
@wclenhardt It's time for us to get the zip code explanatory text.

**Comment by wclenhardt** [comment]
Here you go.  Thx.

"We ask for your zip code as an additional piece of information to help verify your identity."

**Comment by cbcunc** [comment]
The icon should be one of those ubiqitous tiny "info" or "help" style icons (like a question mark in a light blue circle kind of things). I don't know if one already exists in the codebase. It's possible.

**Comment by cbcunc** [comment]
Merged in #138. Thanks, @philtuskha!
