### ISSUE TITLE
Update the 'Create Resource' Page 

### ISSUE THREAD

**Issue by wclenhardt** [myhpom/MyHPOM#59]
- Change labels from 'Resource' to 'Document' 
- Make the default resource a Document resource.  This could be a relabel of an existing resource.
- Hide all other resource types for now.  Put another way, if we can reuse existing resources later by editing, then let's hide them if that's possible.  If it's better/easier to delete, then add back, let's go with that.

**Comment by wclenhardt** [comment]
I wasn't sure if it made sense to put these under one issue, or make them separate. They are connected and I'm guessing they may have connections to other things.

Let me know if we need to discuss further.  Thx.

**Comment by alexlemann** [comment]
This should be closed via #63 .
