### ISSUE TITLE
Profile page changes

### ISSUE THREAD

**Issue by wclenhardt** [myhpom/MyHPOM#69]
Remove the following fields from the UI for editing the profile by commenting out rather than removing all the associated code as it may be useful in the future. This will leave them in the db model schema for now:

Description
User type
Website

On the sign up form, add a required middle name field which will populate the existing optional middle name field on the profile page. Change middle name to required on the profile page.

User type is starred as a required field on the UI. So you may need to use the default in the dropdown, called "unspecified" in the a hidden form field.

In the "About" field group, add the following fields and make the starred fields required:

Address 1
Address 2
City
Zip * (see companion issue #57)
Gender * (a drop down with Male/Female/Other/Prefer Not To Say as the values)
Date of Birth * (a calendar widget)
Last 4 digits of SSN * (and validate this field to insure that it is four and exactly four decimal digits)

Move the existing required State/Province field directly below the new City field. It is a text field, not a drop down, for now. But I anticipate that will change depending on it we continue to support the Country field or if this will be for US use only (I don't believe HS is actually I18N).

Move the existing required Country field below the new Zip field.

Move the User Since field to the top of the About field set.

In the Contact field group, make Phone 1 required.

To the Contact field group add these non-required fields::

Emergency Contact Full Name (one field for full name)
Emergency Contact Relationship (free form text field)
Emergency Contact Phone 1 
Emergency Contact Phone 2
Emergency Contact Email

**Comment by cbcunc** [comment]
@wclenhardt I severely edited edited the description of this issue. Please check it over for correctness.

**Comment by cbcunc** [comment]
@philtuskha An example date widget styled for Hydroshare may be seen by editing the metadata of a resource. Look in the metadata section entitled "Temporal."

**Comment by cbcunc** [comment]
Merged in #123. Thanks, @philtuskha!
