### ISSUE TITLE
sign-in and user profile falls to a second line in nav bar for screen widths <980 pixels

### ISSUE THREAD

**Issue by dsummersl** [myhpom/MyHPOM#88]
This probably means the nav bar covers up the header on a lot of pages if viewed on ipads, low resolution laptops.

![twolineheader](https://user-images.githubusercontent.com/30856/37060371-130e96fc-215e-11e8-8ff9-11031518d956.png)

**Comment by cbcunc** [comment]
Merged in #103. Thanks, @philtuskha.
