### ISSUE TITLE
Add support for dev settings

### ISSUE THREAD

**Issue by dsummersl** [myhpom/MyHPOM#92]
Currently to tweak the developer settings for local development you currently need to edit hydroshare/local_settings.py which are the current production settings. Support a dev_settings.py that is not under version control, that developers can use in their local development without worrying about accidentally modifying a production setting. Add support for a way to choose which environment is used (local_settings or dev_settings), and document it in the README.

**Comment by cbcunc** [comment]
Merged in #101. Well done.

**Comment by cbcunc** [comment]
Also merged companion PR #109.
